spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:h2db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
       enabled: true

  jpa:
    hibernate:
      ddl-auto: validate