spring:
  application:
    name: email-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2
          max-retries: 3
        default-requeue-rejected: false
